#!/bin/bash
clear
c=3 b=4
for j in c b; do
	for i in {0..7}; do
		printf -v $j$i "%b" "\e[${!j}${i}m"
	done
done
bld=$'\e[1m'
rst=$'\e[0m'
inv=$'\e[7m'

user=$(whoami)
host=$(hostname)
os=$(source /etc/os-release && echo $PRETTY_NAME)
kernel=$(hostnamectl | awk -F- '/Kernel/{ OFS="-";NF--; print }'|awk '{print $3}')
wm=$(wmctrl -m | awk 'NR==1 {print $2}')
shell=$(echo "$SHELL" | awk -F/ '{for ( i=1; i <= NF; i++) sub(".", substr(toupper($i),1,1) , $i); print $NF}')
init() {
	init=$(readlink /sbin/init)
	init=${init##*/}
	init=${init%%-*}
	export init
}
init
artist=$(mpc current -p 6601 -f "%artist%")
song=$(mpc current -p 6601 -f "%title%")
album=$(mpc current -p 6601 -f "%album%")

cat <<EOF

${c4} ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
${c4} ▎▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▎${c3}${c4}  ${c2}${c4}  ${c1}${c4}  ▎ ${c5}${c2} ${bld}${c5}$user${rst}@${bld}${c2}$host${rst}
${c4} ▎                            ▎ ${c5}
${c4} ▎   ${c5}█▀▀▀▀▀▀▀▀█${c4}               ▎ ${bld}${c5}OS     ${c3}:${rst} $os
${c4} ▎   ${c5}█        █${c4}               ▎ ${bld}${c5}Kernel ${c3}:${rst} $kernel
${c4} ▎   ${c5}█  █  █  █${c4}               ▎ ${bld}${c5}WM     ${c3}:${rst} $wm
${c4} ▎   ${c5}█        █${c4}               ▎ ${bld}${c5}Shell  ${c3}:${rst} $shell
${c4} ▎   ${c5}▀█▄▄▄▄▄▄█▀${c4}               ▎ ${bld}${c5}Init   ${c3}:${rst} $init
${c4} ▎                            ▎ ${c2}
${c4} ▎                            ▎ ${bld}${c5}Artist ${c3}:${rst} $artist
${c4} ▎   ${c6}sudo rm -rf /* _${c4}       ▎ ${bld}${c5}Song   ${c3}:${rst} $song
${c4} ▎▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▎ ${bld}${c5}Album  ${c3}:${rst} $album


EOF

if  [[ $1 = "-b" ]]; then
	for f in {0..6}; do
		echo -en "\033[$((f+41))m\033[$((f+30))m██▓▒░"
	done
	echo -en "\033[37m██\n"
	echo
	for f in {0..6}; do
		echo -en "\033[$((f+41))m\033[1;$((f+30))m██▓▒░"
	done
	echo -en "\033[1;37m██"
	echo -e "\033[0m"
	echo
else
	:
fi
